default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: loja_tech_development

test:
  <<: *default
  database: loja_tech_test

production:
  <<: *default
  database: loja_tech_production
